# Generated by Django 4.0.3 on 2022-09-16 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Please enter only alphanumeric characters')])),
                ('v_type', models.CharField(choices=[('2', 'Two Wheeler'), ('3', 'Three Wheeler'), ('$', 'Four Wheeler')], max_length=1)),
                ('model', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
    ]
